CREATE TABLE User (
  Id INTEGER PRIMARY KEY NOT NULL,
  UserName VARCHAR(20),
  PassWord VARCHAR(40)
);

CREATE TABLE Blog (
  Id INTEGER PRIMARY KEY NOT NULL,
  Title VARCHAR(50),
  Date DATETIME,
  Content TEXT,
  Author INTEGER,
  FOREIGN KEY (Author) REFERENCES User(Id)
);
